spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  application:
    name: ${SERVICE_NAME:order-service}
server:
  port: ${PORT:8080}
eureka:
  client:
    service-url:
      defaultZone: ${DISCOVERY_SERVER_URL:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true
client:
  user:
    name: ${USER_SERVICE_NAME:user-service}
    apiPath: ${USER_SERVICE_API_PATH:api/v1/users}
  product:
    name: ${PRODUCT_SERVICE_NAME:product-service}
    apiPath: ${PRODUCT_SERVICE_API_PATH:api/v1/products}
